name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  schedule:
  - cron: "* 23 * * *"

jobs:
  build:
    name: Print Date
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "Day $(date)"

      